# Generated by Django 3.2 on 2022-05-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='books',
        ),
        migrations.AddField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(null=True, to='book.Book'),
        ),
    ]
