# Generated by Django 3.2 on 2022-05-22 23:11

import datetime
from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('title', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=80)),
                ('publisher', models.CharField(max_length=80)),
                ('publications_date', models.DateField(blank=True, default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
